#!/bin/bash
ismute=true



mute_status=$(pacmd list-sources | grep -e 'index' -e 'muted:' | sed -n -e '/index: 2/, $p' | head -n2 | tail -n1 | grep yes)
if [ -z "$mute_status" ];
then
    ismute=false
else
    true
fi



if [ ${ismute} = true ]
then
    echo " MUTE"
else 
    echo " LIVE"
fi

