#!/bin/bash
islive=false

mute_status=$(pacmd list-sources | grep -e 'index' -e 'muted:' | grep no)
if [ -z "$mute_status" ];
then
    true
else
    islive=true
fi


if [ ${islive} != true ]
then
    echo " MUTE"
else 
    echo " LIVE"
fi

